[package]
name = "bot_derive"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "1",  features = ["full"] }

[lib]
proc-macro = true
