name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [armv7-unknown-linux-gnueabihf]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/testmest
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../testmest-${{ matrix.target }}.tar.gz testmest
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'testmest*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}